
import com.atlassian.jira.component.ComponentAccessor
import com.onresolve.jira.groovy.user.FieldBehaviours
import groovy.transform.BaseScript

@BaseScript FieldBehaviours fieldBehaviours

def VDA = [
        "P6.1 Process Input":[
                "P6.1.1 Has the project been transferred from development to serial production and" +
                        " is a reliable start guaranteed?",
                "P6.1.2 Are the necessary quantities / production batch sizes of incoming materials available" +
                        " at the agreed upon time and at the correct storage location / work-station?",
                "P6.1.3 Are incoming materials stored appropriately and are the means of transport / packing" +
                        " facilities  suitable for the special characteristics of the incoming materials?",
                "P6.1.4 Are the necessary identifications / records / releases available and allocated" +
                        " appropriately to the incoming materials ?",
                "P6.1.5 Are changes to the product or process made during the serial" +
                        " production tracked and documented?"],

        "P6.2 Process Management/ Work Content":[
                "P6.2.1 Are the requirements of the control plan complete and have they been effectively implemented?",
                "P6.2.2 Does a repeat release for the restart of production take place?",
                "P6.2.3 Are special characteristics managed in the production?",
                "P6.2.4 Are non-released and/or defective parts managed?",
                "P6.2.5 Is the flow of materials and parts secured against mixing / wrong items?"],

        "P6.3 Personnel /Process Support":[
                "P6.3.1 Are the employees able to fulfil their given tasks?",
                "P6.3.2 Do the employees know their responsibilities and authority in the monitoring of" +
                        " the quality of product and process quality?",
                "P6.3.3 Are the necessary personnel resources available?"],

        "P6.4 Material Resources":[
                "P6.4.1 Can the product-specific requirements from the customer be met with" +
                        " the manufacturing equipment?",
                "P6.4.2 Is the maintenance of the manufacturing equipment and tools controlled?",
                "P6.4.3 Can the quality requirements be effectively monitored with the measurement" +
                        " and test facilities in use?",
                "P6.4.4 Are the work and inspection stations appropriate for the needs?",
                "P6.4.5 Are tools, equipment and test equipment stored properly?"],

        "P6.5 Effectiveness of the Process / Efficiency":[
                "P6.5.1 Are there targets set for the manufacturing process?",
                "P6.5.2 Is quality and process data collected in a way that allows analysis?",
                "P6.5.3 In the case of deviations from product and process requirements, are the causes analysed" +
                        " and the corrective actions checked for effectiveness?",
                "P6.5.4 Are processes and products audited regularly?"],

        "P6.6 Process Result / Output":[
                "P6.6.1 Do the quantities / production batch sizes meet the needs and are they systematically" +
                        " directed to the next process step?",
                "P6.6.2 Are products / components stored in an appropriate manner and are transport" +
                        " facilities / packing arrangements suitable for the special" +
                        " characteristics of the products / components?",
                "P6.6.3 Are the necessary records / releases retained?",
                "P6.6.4 Are customer requirements met at the delivery of the final product?"]

]

def ASPICE = [
        "ACQ.4 Supplier Monitoring":[
                "BP1 Agree on and maintain joint processes joint interfaces and information to be exchanged",
                "BP2 Exchange all agreed information",
                "BP3 Review technical development with the supplier",
                "BP4 Review progress of the supplier",
                "BP5 Act to correct deviations",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"
        ],
        "SPL.2 Product Release":["BP2 Define release products",
                                  "BP3 Establish a product release classification and numbering scheme",
                                  "BP4 Define the build activities and build environment",
                                  "BP5 Build the release from configured items",
                                  "BP6 Communicate the type, service level and duration of support for a release",
                                  "BP7 Determine the delivery media type for the release",
                                  "BP8 Identify the packaging for the release media",
                                  "BP9 Define and produce the product release documentation / release notes",
                                  "BP10 Ensure product release approval before delivery",
                                  "BP11 Ensure consistency",
                                  "BP12 Provide a release note",
                                  "BP13 Deliver the release to the intended customer",
                                  "PA2.1A Performance management – KPI",
                                  "PA2.1B Performance management – Process activities planning",
                                  "PA2.2 Work product management",
                                  "PA3.1Process definition process attribute",
                                  "PA3.2 Process deployment process attribute"],
        "SYS.1 Requirements Elicitation":["BP1 Obtain stakeholder requirements and requests",
                                           "BP2 Understand stakeholder expectations",
                                           "BP3 Agree on requirements",
                                           "BP4 Manage stakeholder requirements changes",
                                           "BP5 Establish customer-supplier query communication mechanism",
                                           "PA2.1A Performance management – KPI",
                                           "PA2.1B Performance management – Process activities planning",
                                           "PA2.2 Work product management",
                                           "PA3.1Process definition process attribute",
                                           "PA3.2 Process deployment process attribute"],
        "SYS.2 System Requirements Analysis":["BP1 Specify system requirements",
                                               "BP2 Structure system requirements",
                                               "BP3 Analyze system requirements",
                                               "BP4 Analyze the impact on the operating environment",
                                               "BP5 Develop the verification criteria",
                                               "BP6 Establish bidirectional traceability",
                                               "BP7 Ensure consistency",
                                               "BP8 Communicate agreed system requirements",
                                               "PA2.1A Performance management – KPI",
                                               "PA2.1B Performance management – Process activities planning",
                                               "PA2.2 Work product management",
                                               "PA3.1Process definition process attribute",
                                               "PA3.2 Process deployment process attribute"],
        "SYS.3 System Architectural Design":["BP1 Develop system architectural design",
                                              "BP2 Allocate system requirements",
                                              "BP3 Define interfaces of system elements",
                                              "BP4 Describe dynamic behavior",
                                              "BP5 Evaluate alternative system architectures",
                                              "BP6 Establish bidirectional traceability",
                                              "BP7 Ensure consistency",
                                              "BP8 Communicate agreed system architectural design",
                                              "PA2.1A Performance management – KPI",
                                              "PA2.1B Performance management – Process activities planning",
                                              "PA2.2 Work product management",
                                              "PA3.1Process definition process attribute",
                                              "PA3.2 Process deployment process attribute"],
        "SYS.4 System Integration and Integration Test":[
                "BP1 Develop system integration strategy",
                "BP2 Develop system integration test strategy including regression test strategy",
                "BP3 Develop specification for system integration test",
                "BP4 Integrate system items", "BP5 Select test cases",
                "BP6 Perform system integration test",
                "BP7 Establish bidirectional traceability",
                "BP8 Ensure consistency",
                "BP9 Summarize and communicate results",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SYS.5 System Qualification Test":[
                "BP1 Develop system qualification test strategy including regression test strategy",
                "BP2 Develop specification for system qualification test",
                "BP3 Select test cases",
                "BP4 Test integrated system",
                "BP5 Establish bidirectional traceability",
                "BP6 Ensure consistency",
                "BP7 Summarize and communicate results",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SWE.1 Software Requirement Analysis":["BP1 Specify software requirements",
                                                "BP2 Structure software requirements",
                                                "BP3 Analyze software requirements",
                                                "BP4 Analyze the impact on the operating environment",
                                                "BP5 Develop the verification criteria",
                                                "BP6 Establish bidirectional traceability",
                                                "BP7 Ensure consistency",
                                                "BP8 Communicate agreed software requirements",
                                                "PA2.1A Performance management – KPI",
                                                "PA2.1B Performance management – Process activities planning",
                                                "PA2.2 Work product management",
                                                "PA3.1Process definition process attribute",
                                                "PA3.2 Process deployment process attribute"],
        "SWE.2 Software Architectural Design":["BP1 Develop software architectural design",
                                                "BP2 Allocate software requirements",
                                                "BP3 Define interfaces of software elements",
                                                "BP4 Describe dynamic behavior",
                                                "BP5 Define resource consumption objectives",
                                                "BP6 Evaluate alternative software architectures",
                                                "BP7 Establish bidirectional traceability",
                                                "BP8 Ensure consistency",
                                                "BP9 Communicate agreed software architectural design",
                                                "PA2.1A Performance management – KPI",
                                                "PA2.1B Performance management – Process activities planning",
                                                "PA2.2 Work product management",
                                                "PA3.1Process definition process attribute",
                                                "PA3.2 Process deployment process attribute"],
        "SWE.3 Software Detailed Design and Unit Construction":[
                "BP1 Develop software detailed design",
                "BP2 Define interfaces of software units",
                "BP3 Describe dynamic behavior",
                "BP4 Evaluate software detailed design",
                "BP5 Establish bidirectional traceability",
                "BP6 Ensure consistency",
                "BP7 Communicate agreed software detailed design",
                "BP8 Develop software units",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SWE.4 Software Unit Verification":[
                "BP1 Develop software unit verification strategy including regression strategy",
                "BP2 Develop criteria for unit verification",
                "BP3 Perform static verification of software units",
                "BP4 Test software units",
                "BP5 Establish bidirectional traceability",
                "BP6 Ensure consistency",
                "BP7 Summarize and communicate results",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SWE.5 Software Integration and Integration Test":[
                "BP1 Develop software integration strategy",
                "BP2 Develop software integration test strategy including regression test strategy",
                "BP3 Develop specification for software integration test",
                "BP4 Integrate software units and software items",
                "BP5 Select test cases",
                "BP6 Perform software integration test",
                "BP7 Establish bidirectional traceability",
                "BP8 Ensure consistency",
                "BP9 Summarize and communicate results",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SWE.6 Software Qualification Test":[
                "BP1 Develop software qualification test strategy including regression test strategy",
                "BP2 Develop specification for software qualification test",
                "BP3 Select test cases",
                "BP4 Test integrated software",
                "BP5 Establish bidirectional traceability",
                "BP6 Ensure consistency",
                "BP7 Summarize and communicate results",
                "PA2.1A Performance management – KPI",
                "PA2.1B Performance management – Process activities planning",
                "PA2.2 Work product management",
                "PA3.1Process definition process attribute",
                "PA3.2 Process deployment process attribute"],
        "SUP.1 Quality Assurance":["BP1 Develop a project quality assurance strategy",
                                    "BP2 Assure quality of work products",
                                    "BP3 Assure quality of process activities",
                                    "BP4 Summarize and communicate quality assurance activities and results",
                                    "BP5 Ensure resolution of non-conformances",
                                    "BP6 Implement an escalation mechanism",
                                    "PA2.1A Performance management – KPI",
                                    "PA2.1B Performance management – Process activities planning",
                                    "PA2.2 Work product management",
                                    "PA3.1Process definition process attribute",
                                    "PA3.2 Process deployment process attribute"],
        "SUP.2 Verification":["BP1 Develop a verification strategy",
                               "BP2 Develop criteria for verification",
                               "BP3 Conduct verification",
                               "BP4 Determine and track actions for verification results",
                               "BP5 Report verification results",
                               "PA2.1A Performance management – KPI",
                               "PA2.1B Performance management – Process activities planning",
                               "PA2.2 Work product management",
                               "PA3.1Process definition process attribute",
                               "PA3.2 Process deployment process attribute"],
        "SUP.4 Joint Review":["BP1 Define review elements",
                               "BP2 Establish a mechanism to handle review outcomes",
                               "BP3 Prepare joint review",
                               "BP4 Conduct joint reviews",
                               "BP5 Distribute the results",
                               "BP6 Determine actions for review results",
                               "BP7 Track actions for review results",
                               "BP8 Identify and record problems",
                               "PA2.1A Performance management – KPI",
                               "PA2.1B Performance management – Process activities planning",
                               "PA2.2 Work product management",
                               "PA3.1Process definition process attribute",
                               "PA3.2 Process deployment process attribute"],
        "SUP.7 Documentation":["BP1 Develop a documentation management strategy",
                                "BP2 Establish standards for documentation",
                                "BP3 Specify documentation requirements",
                                "BP4 Identify the relevant documentation to be produced",
                                "BP5 Develop documentation",
                                "BP6 Check documentation",
                                "BP7 Distribute documentation",
                                "BP8 Maintain documentation",
                                "PA2.1A Performance management – KPI",
                                "PA2.1B Performance management – Process activities planning",
                                "PA2.2 Work product management",
                                "PA3.1Process definition process attribute",
                                "PA3.2 Process deployment process attribute"],
        "SUP.8 Configuration Management":["BP1 Develop a configuration management strategy",
                                           "BP2 Identify configuration items",
                                           "BP3 Establish a configuration management system",
                                           "BP4 Establish branch management",
                                           "BP5 Control modifications and releases",
                                           "BP6 Establish baselines",
                                           "BP7 Report configuration status",
                                           "BP8 Verify the information about configuration items",
                                           "BP9 Manage the storage of configuration items and baselines",
                                           "PA2.1A Performance management – KPI",
                                           "PA2.1B Performance management – Process activities planning",
                                           "PA2.2 Work product management",
                                           "PA3.1Process definition process attribute",
                                           "PA3.2 Process deployment process attribute"],
        "SUP.9 Problem Resolution Management":["BP1 Develop a problem resolution management strategy",
                                                "BP2 Identify and record the problem",
                                                "BP3 Record the status of problems",
                                                "BP4 Diagnose the cause and determine the impact of the problem",
                                                "BP5 Authorize urgent resolution action",
                                                "BP6 Raise alert notifications",
                                                "BP7 Initiate problem resolution",
                                                "BP8 Track problems to closure",
                                                "BP9 Analyze problem trends",
                                                "PA2.1A Performance management – KPI",
                                                "PA2.1B Performance management – Process activities planning",
                                                "PA2.2 Work product management",
                                                "PA3.1Process definition process attribute",
                                                "PA3.2 Process deployment process attribute"],
        "SUP.10 Change Request Management":["BP1 Develop a change request management strategy",
                                             "BP2 Identify and record the change requests",
                                             "BP3 Record the status of change requests",
                                             "BP4 Analyze and assess change requests",
                                             "BP5 Approve change requests before implementation",
                                             "BP6 Review the implementation of change requests",
                                             "BP7 Track problems to closure",
                                             "BP8 Establish bidirectional traceability",
                                             "PA2.1A Performance management – KPI",
                                             "PA2.1B Performance management – Process activities planning",
                                             "PA2.2 Work product management",
                                             "PA3.1Process definition process attribute",
                                             "PA3.2 Process deployment process attribute"],
        "MAN.3 Project Management":["BP1 Define the scope of work",
                                     "BP2 Define project life cycle",
                                     "BP3 Evaluate feasibility of the project",
                                     "BP4 Define, monitor and adjust project activities",
                                     "BP5 Define, monitor and adjust project estimates and resources",
                                     "BP6 Ensure required skills, knowledge and experience",
                                     "BP7 Identify, monitor and adjust project interfaces and agreed commitments",
                                     "BP8 Define, monitor and adjust project schedule",
                                     "BP9 Ensure consistency",
                                     "BP10 Review and report progress of the project",
                                     "PA2.1A Performance management – KPI",
                                     "PA2.1B Performance management – Process activities planning",
                                     "PA2.2 Work product management",
                                     "PA3.1Process definition process attribute",
                                     "PA3.2 Process deployment process attribute"],
        "MAN.5 Risk Management":["BP1 Establish risk management scope",
                                  "BP2 Define risk management strategies",
                                  "BP3 Identify risks",
                                  "BP4 Analyze risks",
                                  "BP5 Define risk treatment actions",
                                  "BP6 Monitor risks",
                                  "BP7 Take corrective actions",
                                  "PA2.1A Performance management – KPI",
                                  "PA2.1B Performance management – Process activities planning",
                                  "PA2.2 Work product management",
                                  "PA3.1Process definition process attribute",
                                  "PA3.2 Process deployment process attribute"],
        "MAN.6 Measurement":["BP1 Establish organizational commitment for measurement",
                              "BP2 Develop measurement strategy",
                              "BP3 Identify measurement information needs",
                              "BP4 Specify measures",
                              "BP5 Perform measurement activities",
                              "BP6 Retrieve measurement data",
                              "BP7 Analyze measures",
                              "BP8 Use measurement information for decision-making",
                              "BP9 Communicate measures",
                              "BP10 Evaluate information products and measurement activities",
                              "BP11 Communicate potential improvements",
                              "PA2.1A Performance management – KPI",
                              "PA2.1B Performance management – Process activities planning",
                              "PA2.2 Work product management",
                              "PA3.1Process definition process attribute",
                              "PA3.2 Process deployment process attribute"],
        "PIM.3 Process Improvement":["BP1 Establish commitment",
                                      "BP2 Identify Issues",
                                      "BP3 Establish process improvement goals",
                                      "BP4 Prioritize improvements",
                                      "BP5 Plan process changes",
                                      "BP6 Implement process changes",
                                      "BP7 Confirm process improvement",
                                      "BP8 Communicate results of improvement",
                                      "BP9 Evaluate the results of the improvement project",
                                      "PA2.1A Performance management – KPI",
                                      "PA2.1B Performance management – Process activities planning",
                                      "PA2.2 Work product management",
                                      "PA3.1Process definition process attribute",
                                      "PA3.2 Process deployment process attribute"],
        "REU.2 Reuse Program Management":["BP1 Define organizational reuse strategy",
                                           "BP2 Identify domains for potential reuse",
                                           "BP3 Assess domains for potential reuse",
                                           "BP4 Assess reuse maturity",
                                           "BP5 Evaluate reuse proposals",
                                           "BP6 Implement the reuse program",
                                           "BP7 Get feedback from reuse",
                                           "BP8 Monitor reuse",
                                           "PA2.1A Performance management – KPI",
                                           "PA2.1B Performance management – Process activities planning",
                                           "PA2.2 Work product management",
                                           "PA3.1Process definition process attribute",
                                           "PA3.2 Process deployment process attribute"]
]

def cfProcessGroup = getFieldByName("Process Group")
def cfPractice = getFieldByName("Practice")
def cfSubPractice = getFieldByName("Sub Practice")
def cfStandard = getFieldByName("Standard")

def standardValue = cfStandard.getValue() as String
def ProcessGroup = cfProcessGroup.getValue() as String
def Practice = cfPractice.getValue() as String
def SubPracticeValues

if (standardValue == "VDA 6.3" && ProcessGroup == "P6 Process analysis/Production") {
    SubPracticeValues = VDA.get(Practice)
    cfSubPractice.setRequired(Boolean.TRUE)
} else if (standardValue == "ASPICE") {
    SubPracticeValues = ASPICE.get(Practice)
    cfSubPractice.setRequired(Boolean.TRUE)
} else {
    cfSubPractice.setRequired(Boolean.FALSE)
}

def customFieldManager = ComponentAccessor.customFieldManager
def moduleCFConfig = customFieldManager.getCustomFieldObject(cfSubPractice?.fieldId)?.getRelevantConfig(issueContext)
def optionManager = ComponentAccessor.getOptionsManager()
def optionsForSubPractice = optionManager.getOptions(moduleCFConfig).findAll { it.value in SubPracticeValues }
def optionMap = new LinkedHashMap<String, String>()
optionMap["-1"] = "None"

optionsForSubPractice.collectEntries(optionMap) { option ->
    def optionValue = option.value
    [(option.optionId.toString()):optionValue]
}
cfSubPractice.setFieldOptions(optionMap)
